name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add SWIPL repo
      run: sudo apt-add-repository "ppa:swi-prolog/stable" -y
    - name: Install dependencies
      run: sudo apt update && sudo apt install swi-prolog-nox libjwt-dev -y
    - name: make
      run: make
